import type { Metadata } from 'next';
import { Poppins, Roboto } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';

import '@/stylesheets/globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'AmbientAI',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='pt-BR'>
      <body className={`${poppins.className} ${roboto.variable} antialiased`}>
        {children}
        <Toaster richColors position='top-right' theme='light' />
      </body>
    </html>
  );
}
