import type { Metadata } from 'next';
import { Poppins, Roboto } from 'next/font/google';
import { getCurrentUser } from '@/services/auth.service';
import { SessionProvider } from '@/providers/session.provider';

import '@/stylesheets/globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'AmbientAI',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getCurrentUser();

  return (
    <html lang='pt-BR'>
      <SessionProvider session={session}>
        <body className={`${poppins.className} ${roboto.variable} antialiased`}>{children}</body>
      </SessionProvider>
    </html>
  );
}
