volumes:
  postgres-data:

services:
  api:
    image: rgomes98/ambientai-api:latest
    container_name: api
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=America/Sao_Paulo
    env_file: .env

  nginx:
    image: nginx:1.21-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf.template:/etc/nginx/templates/10-nginx.conf.template:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
