version: '3.8'

volumes:
  postgres-data:

services:
  api:
    build: .
    container_name: api
    restart: always
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env

  nginx:
    image: nginx:1.21-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
